name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Latest stable version

      - name: Setup Pages
        uses: actions/configure-pages@v3  # ✅ Latest stable version

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1  # ✅ Jekyll only has v1
        with:
          source: . # Root directory
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # ✅ Latest stable version

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # ✅ Latest stable version
